#name of the job
name: Testing Job

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Needed for HTTP request
  repository_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: 
      group: genies-internal-runner
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v3
      
      - uses: geniesinc/security-pipelines/.github/workflows/build_and_push.yaml@SRE/buildxHotfix
        # with:
        #   root: "test"
        #   service: "test"
        #   context: "."
        # secrets: inherit
