#name of the job
name: Testing Job

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Needed for HTTP request
  repository_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on:
      group: genies-runners

    steps:
      - uses: actions/checkout@v3
      
      - name: sleep for 5 mins
        run: |
          sleep 300
