#name of the job
name: Art Runner Testing

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      artifact:
        description: 'Name of the artifact to download'
        required: true
  # Needed for HTTP request
  repository_dispatch:
    inputs:
      artifact:
        description: 'Name of the artifact to download'
        required: true
adjustment
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: 
      group: genies-art-runners
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    env:
      start_bucket_name: "runner-poc-bucket"
      result_bucket_name: "runner-poc-testing-result"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Install AWS cli
        uses: unfor19/install-aws-cli-action@v1

      - name: Assume an AWS role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::583625886946:role/genies_deployer-role #arn:aws:iam::608392574519:role/devkit-s3-manager
          aws-region: us-west-2
        
      - name: Download a file from the starting bucket
        run: |
          aws s3 cp s3://${{ env.start_bucket_name }}/${{ inputs.artifact }} ${{ inputs.artifact }}
        shell: bash
        
      - name: Process the file
        run: |
          echo 'This file is now processed!' >> ${{ inputs.artifact }}
        shell: bash
      
      - name: Upload a processed file to S3
        run: |
          aws s3 cp ${{ inputs.artifact }} s3://${{ env.result_bucket_name }}/processed-${{ inputs.artifact }}
        shell: bash
