name: Art Runner Testing

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  repository_dispatch:
    types: [retry_job]
    # inputs:
    #   artifact:
    #     description: 'Name of the artifact to download'
    #     required: true
    #   start-bucket-name:
    #     description: 'Name of the bucket'
    #     required: true


jobs:

  build:
    runs-on: genies-internal-content-runner
    timeout-minutes: 1
    env:
      start_bucket_name: "genies-asset-bucket-test"
      result_bucket_name: "runner-poc-testing-result"
      asset: "0a225c6b-c9c3-47b2-8818-de8a86a89190.zip"
      
    steps:
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v3
      
      - name: Install AWS cli
        uses: unfor19/install-aws-cli-action@v1

      # - name: Assume an AWS role
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     role-to-assume: arn:aws:iam::583625886946:role/genies_deployer-role #arn:aws:iam::608392574519:role/devkit-s3-manager
      #     aws-region: us-west-2
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_RUNNERS_DEV_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_RUNNERS_DEV_SECRET_KEY }}
          aws-region: 'us-west-2'
        
      - name: Download a file from the starting bucket
        run: |
          aws s3 cp s3://${{ env.start_bucket_name }}/${{ env.asset }} ${{ env.asset }}
        shell: bash
        
      # Build
      - name: Build Addressables Content for android
        uses: geniesinc/game-ci-unity-builder@raad/no-quit
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: 'android'
          buildMethod: 'Genies.Editor.Build.HeadlessDynamicBuildScript.HeadlessBuild'
          customParameters: '-packageUrlOrPath ${{ env.asset }} -platforms android -buildProfile Dynamic'
      
      
      # - name: Upload a processed file to S3
      #   run: |
      #     aws s3 cp ${{ inputs.artifact }} s3://${{ env.result_bucket_name }}/processed-${{ inputs.artifact }}
      #   shell: bash
